name: Export & Unpack from Dev
on:
  workflow_dispatch: {}

jobs:
  export-unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PAC
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      - name: Power Platform Auth
        run: |
          pac auth create --tenant ${{ secrets.PP_TENANT_ID }}             --url ${{ secrets.PP_DEV_ENV_URL }}             --applicationId ${{ secrets.PP_CLIENT_ID }}             --clientSecret ${{ secrets.PP_CLIENT_SECRET }}
      - name: Export solution (unmanaged)
        run: |
          mkdir -p ./tmp
          pac solution export             --name YourSolutionName             --outputFile ./tmp/solution.zip             --managed false
      - name: Unpack solution
        run: |
          pac solution unpack             --zipfile ./tmp/solution.zip             --folder ./solutions/src             --processCanvasApps true             --allowDelete true
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Unpacked solution from Dev" || echo "No changes to commit"
          git push
